//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2024-04-08 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
#ifndef _DefaultMod_anonym_h
#define _DefaultMod_anonym_h


#include "DefaultMod_userdef.h"
#include "metaiv.h"

extern const Quote quote_UP;

extern const Quote quote_DOWN;

extern const Quote quote_LEFT;

extern const Quote quote_RIGHT;

class TYPE_DefaultMod_RobotMonitor;
#define TYPE_DefaultMod_Move Generic
#ifndef TAG_quote_UP
#define TAG_quote_UP (TAG_DefaultMod + 1)
#endif // TAG_quote_UP

#ifndef TAG_quote_DOWN
#define TAG_quote_DOWN (TAG_DefaultMod + 2)
#endif // TAG_quote_DOWN

#ifndef TAG_quote_LEFT
#define TAG_quote_LEFT (TAG_DefaultMod + 3)
#endif // TAG_quote_LEFT

#ifndef TAG_quote_RIGHT
#define TAG_quote_RIGHT (TAG_DefaultMod + 4)
#endif // TAG_quote_RIGHT

#ifndef TAG_TYPE_DefaultMod_RobotMonitor
#define TAG_TYPE_DefaultMod_RobotMonitor (TAG_DefaultMod + 5)
#endif // TAG_TYPE_DefaultMod_RobotMonitor



#endif // _DefaultMod_anonym_h
