//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2024-04-08 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//


#include "DefaultMod_userdef.h"
#include "metaiv.h"
#include "DefaultMod.h"

#if !DEF_quote_UP && DECL_quote_UP
#define DEF_quote_UP 1

const Quote quote_UP (L"UP");

#endif // DEF_quote_UP

#if !DEF_quote_DOWN && DECL_quote_DOWN
#define DEF_quote_DOWN 1

const Quote quote_DOWN (L"DOWN");

#endif // DEF_quote_DOWN

#if !DEF_quote_LEFT && DECL_quote_LEFT
#define DEF_quote_LEFT 1

const Quote quote_LEFT (L"LEFT");

#endif // DEF_quote_LEFT

#if !DEF_quote_RIGHT && DECL_quote_RIGHT
#define DEF_quote_RIGHT 1

const Quote quote_RIGHT (L"RIGHT");

#endif // DEF_quote_RIGHT


