//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2024-04-08 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//
#ifndef _DefaultMod_h
#define _DefaultMod_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "DefaultMod_anonym.h"


enum {
  vdm_DefaultMod_RobotMonitor = TAG_TYPE_DefaultMod_RobotMonitor,
  length_DefaultMod_RobotMonitor = 3,
  pos_DefaultMod_RobotMonitor_col = 1,
  pos_DefaultMod_RobotMonitor_row = 2,
  pos_DefaultMod_RobotMonitor_move = 3
};

class TYPE_DefaultMod_RobotMonitor : public Record {
public:
  TYPE_DefaultMod_RobotMonitor () : Record(TAG_TYPE_DefaultMod_RobotMonitor, 3) {}

  TYPE_DefaultMod_RobotMonitor &Init (const Int &p1, const Int &p2, const Generic &p3);
  TYPE_DefaultMod_RobotMonitor (const Common &c) : Record(c) {}

  const wchar_t * GetTypeName () const   {
    return L"TYPE_DefaultMod_RobotMonitor";
  }

  Int get_col () const;
  void set_col (const Int &p);
  Int get_row () const;
  void set_row (const Int &p);
  Generic get_move () const;
  void set_move (const Generic &p);
};

Bool vdm_DefaultMod_inv_RobotMonitor (const TYPE_DefaultMod_RobotMonitor &);

extern Int vdm_DefaultMod_MAX;

extern Int vdm_DefaultMod_MIN;

extern Int vdm_DefaultMod_currentCol;

extern Int vdm_DefaultMod_currentRow;

extern Generic vdm_DefaultMod_currentMove;

void init_DefaultMod ();

void vdm_DefaultMod_GetCol ();

Bool vdm_DefaultMod_pre_GetCol (const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_post_GetCol (const TYPE_DefaultMod_RobotMonitor &, const TYPE_DefaultMod_RobotMonitor &);

void vdm_DefaultMod_GetRow ();

Bool vdm_DefaultMod_pre_GetRow (const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_post_GetRow (const TYPE_DefaultMod_RobotMonitor &, const TYPE_DefaultMod_RobotMonitor &);

void vdm_DefaultMod_MoveUp ();

Bool vdm_DefaultMod_pre_MoveUp (const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_post_MoveUp (const TYPE_DefaultMod_RobotMonitor &, const TYPE_DefaultMod_RobotMonitor &);

void vdm_DefaultMod_GetMove ();

Bool vdm_DefaultMod_pre_GetMove (const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_post_GetMove (const TYPE_DefaultMod_RobotMonitor &, const TYPE_DefaultMod_RobotMonitor &);

void vdm_DefaultMod_MoveDown ();

Bool vdm_DefaultMod_pre_MoveDown (const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_post_MoveDown (const TYPE_DefaultMod_RobotMonitor &, const TYPE_DefaultMod_RobotMonitor &);

void vdm_DefaultMod_MoveLeft ();

Bool vdm_DefaultMod_pre_MoveLeft (const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_post_MoveLeft (const TYPE_DefaultMod_RobotMonitor &, const TYPE_DefaultMod_RobotMonitor &);

void vdm_DefaultMod_MoveRight ();

Bool vdm_DefaultMod_pre_MoveRight (const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_post_MoveRight (const TYPE_DefaultMod_RobotMonitor &, const TYPE_DefaultMod_RobotMonitor &);

Bool vdm_DefaultMod_init_uRobotMonitor (const TYPE_DefaultMod_RobotMonitor &);


#endif // _DefaultMod_h
