//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2024-04-08 by the VDM-SL to C++ Code Generator
// (v9.0.7 - Sat 09-Jun-2018 09:35:14 +0900)
//

#include "DefaultMod.h"


Int vdm_DefaultMod_MAX;

Int vdm_DefaultMod_MIN;

Int vdm_DefaultMod_currentCol;

Int vdm_DefaultMod_currentRow;

Generic vdm_DefaultMod_currentMove;

static Int vdm_DefaultMod_col;

static Int vdm_DefaultMod_row;

static Generic vdm_DefaultMod_move;

TYPE_DefaultMod_RobotMonitor &TYPE_DefaultMod_RobotMonitor::Init (const Int &p1, const Int &p2, const Generic &p3) {
  this->SetField(1, p1);
  this->SetField(2, p2);
  this->SetField(3, p3);
  return * this;
}

Int TYPE_DefaultMod_RobotMonitor::get_col () const {
  return this->GetInt(1);
}

void TYPE_DefaultMod_RobotMonitor::set_col (const Int &p) {
  this->SetField(1, p);
}

Int TYPE_DefaultMod_RobotMonitor::get_row () const {
  return this->GetInt(2);
}

void TYPE_DefaultMod_RobotMonitor::set_row (const Int &p) {
  this->SetField(2, p);
}

Generic TYPE_DefaultMod_RobotMonitor::get_move () const {
  return this->GetField(3);
}

void TYPE_DefaultMod_RobotMonitor::set_move (const Generic &p) {
  this->SetField(3, p);
}

#ifndef DEF_DefaultMod_inv_RobotMonitor

Bool vdm_DefaultMod_inv_RobotMonitor (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_c (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_r (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_m (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool((((((vdm_DefaultMod_r.GetValue() >= vdm_DefaultMod_MIN.GetValue()) ? (vdm_DefaultMod_r.GetValue() <= vdm_DefaultMod_MAX.GetValue()) : false) ? true : (((vdm_DefaultMod_c.GetValue() >= vdm_DefaultMod_MIN.GetValue()) ? (vdm_DefaultMod_c.GetValue() <= vdm_DefaultMod_MAX.GetValue()) : false) ? (vdm_DefaultMod_m == Quote(L"LEFT")) : false)) ? true : (vdm_DefaultMod_m == Quote(L"RIGHT"))) ? true : (vdm_DefaultMod_m == Quote(L"UP"))) ? true : (vdm_DefaultMod_m == Quote(L"DOWN")));
}

#endif // DEF_DefaultMod_inv_RobotMonitor


void init_DefaultMod_VDMLib () {
  VDMGetDefaultRecInfoMap().NewTag(TAG_TYPE_DefaultMod_RobotMonitor, 3);
  VDMGetDefaultRecInfoMap().SetSymTag(TAG_TYPE_DefaultMod_RobotMonitor, L"DefaultMod`RobotMonitor");
  AddRecordTag(L"DefaultMod`RobotMonitor", TAG_TYPE_DefaultMod_RobotMonitor);
}

#include "DefaultMod_userimpl.cpp"


void init_DefaultMod () {
  init_DefaultMod_VDMLib();
  vdm_DefaultMod_MAX = Int(6);
  vdm_DefaultMod_MIN = Int(1);
  vdm_DefaultMod_currentRow = Int(1);
  vdm_DefaultMod_currentCol = Int(1);
  vdm_DefaultMod_currentMove = Nil();
  vdm_DefaultMod_col = Int(1);
  vdm_DefaultMod_row = Int(1);
  vdm_DefaultMod_move = Nil();
}

#ifndef DEF_DefaultMod_init_uRobotMonitor

Bool vdm_DefaultMod_init_uRobotMonitor (const TYPE_DefaultMod_RobotMonitor &vdm_DefaultMod_RM) {
  return Bool(vdm_DefaultMod_RM == TYPE_DefaultMod_RobotMonitor().Init(Int(1), Int(1), Nil()));
}

#endif // DEF_DefaultMod_init_uRobotMonitor

#ifndef DEF_DefaultMod_pre_GetCol

Bool vdm_DefaultMod_pre_GetCol (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(true);
}

#endif // DEF_DefaultMod_pre_GetCol

#ifndef DEF_DefaultMod_post_GetCol

Bool vdm_DefaultMod_post_GetCol (const TYPE_DefaultMod_RobotMonitor &var_1_1, const TYPE_DefaultMod_RobotMonitor &var_2_2) {
  const Int _vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int _vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic _vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  const Int vdm_DefaultMod_col (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_2_2.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(vdm_DefaultMod_currentCol.GetValue() == vdm_DefaultMod_col.GetValue());
}

#endif // DEF_DefaultMod_post_GetCol

#ifndef DEF_DefaultMod_pre_GetRow

Bool vdm_DefaultMod_pre_GetRow (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(true);
}

#endif // DEF_DefaultMod_pre_GetRow

#ifndef DEF_DefaultMod_post_GetRow

Bool vdm_DefaultMod_post_GetRow (const TYPE_DefaultMod_RobotMonitor &var_1_1, const TYPE_DefaultMod_RobotMonitor &var_2_2) {
  const Int _vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int _vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic _vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  const Int vdm_DefaultMod_col (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_2_2.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(vdm_DefaultMod_currentRow.GetValue() == vdm_DefaultMod_row.GetValue());
}

#endif // DEF_DefaultMod_post_GetRow

#ifndef DEF_DefaultMod_pre_MoveUp

Bool vdm_DefaultMod_pre_MoveUp (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool((!(vdm_DefaultMod_currentMove == Quote(L"UP"))) ? true : (((!(vdm_DefaultMod_currentMove == Nil())) ? (vdm_DefaultMod_row.GetValue() > vdm_DefaultMod_MIN.GetValue()) : false) ? (vdm_DefaultMod_row.GetValue() < vdm_DefaultMod_MAX.GetValue()) : false));
}

#endif // DEF_DefaultMod_pre_MoveUp

#ifndef DEF_DefaultMod_post_MoveUp

Bool vdm_DefaultMod_post_MoveUp (const TYPE_DefaultMod_RobotMonitor &var_1_1, const TYPE_DefaultMod_RobotMonitor &var_2_2) {
  const Int _vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int _vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic _vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  const Int vdm_DefaultMod_col (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_2_2.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool((vdm_DefaultMod_currentRow.GetValue() == (_vdm_DefaultMod_row - vdm_DefaultMod_row).GetValue()) ? (vdm_DefaultMod_currentMove == Quote(L"UP")) : false);
}

#endif // DEF_DefaultMod_post_MoveUp

#ifndef DEF_DefaultMod_pre_GetMove

Bool vdm_DefaultMod_pre_GetMove (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(true);
}

#endif // DEF_DefaultMod_pre_GetMove

#ifndef DEF_DefaultMod_post_GetMove

Bool vdm_DefaultMod_post_GetMove (const TYPE_DefaultMod_RobotMonitor &var_1_1, const TYPE_DefaultMod_RobotMonitor &var_2_2) {
  const Int _vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int _vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic _vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  const Int vdm_DefaultMod_col (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_2_2.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(vdm_DefaultMod_currentMove == vdm_DefaultMod_currentMove);
}

#endif // DEF_DefaultMod_post_GetMove

#ifndef DEF_DefaultMod_pre_MoveDown

Bool vdm_DefaultMod_pre_MoveDown (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(((!(vdm_DefaultMod_currentMove == Quote(L"DOWN"))) ? (vdm_DefaultMod_row.GetValue() > vdm_DefaultMod_MIN.GetValue()) : false) ? (vdm_DefaultMod_row.GetValue() < vdm_DefaultMod_MAX.GetValue()) : false);
}

#endif // DEF_DefaultMod_pre_MoveDown

#ifndef DEF_DefaultMod_post_MoveDown

Bool vdm_DefaultMod_post_MoveDown (const TYPE_DefaultMod_RobotMonitor &var_1_1, const TYPE_DefaultMod_RobotMonitor &var_2_2) {
  const Int _vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int _vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic _vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  const Int vdm_DefaultMod_col (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_2_2.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool((vdm_DefaultMod_currentRow.GetValue() == (_vdm_DefaultMod_row + vdm_DefaultMod_row).GetValue()) ? (vdm_DefaultMod_currentMove == Quote(L"DOWN")) : false);
}

#endif // DEF_DefaultMod_post_MoveDown

#ifndef DEF_DefaultMod_pre_MoveLeft

Bool vdm_DefaultMod_pre_MoveLeft (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool((((!(vdm_DefaultMod_currentMove == Quote(L"LEFT"))) ? (!(vdm_DefaultMod_currentMove == Nil())) : false) ? (vdm_DefaultMod_col.GetValue() > vdm_DefaultMod_MIN.GetValue()) : false) ? (vdm_DefaultMod_col.GetValue() < vdm_DefaultMod_MAX.GetValue()) : false);
}

#endif // DEF_DefaultMod_pre_MoveLeft

#ifndef DEF_DefaultMod_post_MoveLeft

Bool vdm_DefaultMod_post_MoveLeft (const TYPE_DefaultMod_RobotMonitor &var_1_1, const TYPE_DefaultMod_RobotMonitor &var_2_2) {
  const Int _vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int _vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic _vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  const Int vdm_DefaultMod_col (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_2_2.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool((vdm_DefaultMod_currentCol.GetValue() == (_vdm_DefaultMod_col - vdm_DefaultMod_col).GetValue()) ? (vdm_DefaultMod_currentMove == Quote(L"LEFT")) : false);
}

#endif // DEF_DefaultMod_post_MoveLeft

#ifndef DEF_DefaultMod_pre_MoveRight

Bool vdm_DefaultMod_pre_MoveRight (const TYPE_DefaultMod_RobotMonitor &var_1_1) {
  const Int vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool(((!(vdm_DefaultMod_currentMove == Quote(L"RIGHT"))) ? (vdm_DefaultMod_col.GetValue() > vdm_DefaultMod_MIN.GetValue()) : false) ? (vdm_DefaultMod_col.GetValue() < vdm_DefaultMod_MAX.GetValue()) : false);
}

#endif // DEF_DefaultMod_pre_MoveRight

#ifndef DEF_DefaultMod_post_MoveRight

Bool vdm_DefaultMod_post_MoveRight (const TYPE_DefaultMod_RobotMonitor &var_1_1, const TYPE_DefaultMod_RobotMonitor &var_2_2) {
  const Int _vdm_DefaultMod_col (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int _vdm_DefaultMod_row (var_1_1.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic _vdm_DefaultMod_move (var_1_1.GetField(pos_DefaultMod_RobotMonitor_move));
  const Int vdm_DefaultMod_col (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_col));
  const Int vdm_DefaultMod_row (var_2_2.GetInt(pos_DefaultMod_RobotMonitor_row));
  const Generic vdm_DefaultMod_move (var_2_2.GetField(pos_DefaultMod_RobotMonitor_move));
  return Bool((vdm_DefaultMod_currentCol.GetValue() == (_vdm_DefaultMod_col + vdm_DefaultMod_col).GetValue()) ? (vdm_DefaultMod_currentMove == Quote(L"RIGHT")) : false);
}

#endif // DEF_DefaultMod_post_MoveRight


